export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_BURRITO_START = 'PURCHASE_BURRITO_START';
export const PURCHASE_BURRITO_SUCCESS = 'PURCHASE_BURRITO_SUCCESS';
export const PURCHASE_BURRITO_FAIL = 'PURCHASE_BURRITO_FAIL';
